Update scripts.

diff --git a/scripts/myyt b/scripts/myyt
--- a/scripts/myyt
+++ b/scripts/myyt
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #dependencies: mpv youtube-dl fzf rofi/dmenu
 # search videos and playlists on youtube and play them in mpv, without an API
 # usage:
@@ -6,10 +6,22 @@
 # yt search query		takes input from the passed arg, prompts using fzf
 # yt -r					takes input and prompts using rofi ($guicmd)
 
+
+# grep the id and title
+# return them in format id (type) title
+getresults() {
+	  grep "$1" $responsecache |\
+		awk -F\" -v p="$2" '{ print $1 "\t" p " " $NF}'
+}
+
+cachedir=$HOME/.cache/myyt
+test -d $cachedir || mkdir -p $cachedir
+
 defcmd="fzf"
-#guicmd="rofi -dmenu -i" #uncomment next line for dmenu
-guicmd="dmenu -x 768 -y 5.4 -z 384 -i -l 15"
+guicmd="dmenu -c -l 15  -i"
 promptcmd="$defcmd"
+responsecache="$cachedir/response.html"
+
 if [ -z "$*" ]; then
 	echo -n "Youtube: "
 	read -r query
@@ -21,43 +33,46 @@ else
 	esac
 fi
 if [ -z "$query" ]; then exit; fi
+
 # sanitise the query
-query=$(sed \
+query=$(echo $query | sed \
 	-e 's|+|%2B|g'\
 	-e 's|#|%23|g'\
 	-e 's|&|%26|g'\
-	-e 's| |+|g'\
-	<<< "$query")
+  -e 's| |+|g')
+
+
 # fetch the results with the $query and
 # delete all escaped characters
-response="$(curl -s "https://www.youtube.com/results?search_query=$query" |\
-	sed 's|\\.||g')"
+curl -s "https://www.youtube.com/results?search_query=$query" |\
+	sed 's|\\.||g' -o $responsecache
+
 # if unable to fetch the youtube results page, inform and exit
-if ! grep -q "script" <<< "$response"; then echo "unable to fetch yt"; exit 1; fi
+if ! grep "script" $responsecache >/dev/null; then echo "unable to fetch yt"; exit 1; fi
+
 # regex expression to match video and playlist entries from yt result page
-vgrep='"videoRenderer":{"videoId":"\K.{11}".+?"text":".+?[^\\](?=")'
-pgrep='"playlistRenderer":{"playlistId":"\K.{34}?","title":{"simpleText":".+?[^\"](?=")'
-# grep the id and title
-# return them in format id (type) title
-getresults() {
-	  grep -oP "$1" <<< "$response" |\
-		awk -F\" -v p="$2" '{ print $1 "\t" p " " $NF}'
-}
+vgrep='"videoRenderer":{"videoId":"[[:alpha:]]{11}"'
+# vgrep='"videoRenderer":{"videoId":"[[:alpha:]]{11}".+?"text":".+?[^\\](?=")'
+# pgrep='"playlistRenderer":{"playlistId":"\K.{34}?","title":{"simpleText":".+?[^\"](?=")'
+
 # get the list of videos/playlists and their ids in videoids and playlistids
-videoids=$(getresults "$vgrep")
-playlistids=$(getresults "$pgrep" "(playlist)")
+videoids=$(grep -o "$vgrep" $responsecache | awk -F\" '{print $6}')
+# videoids=$(getresults "$vgrep")
+# playlistids=$(getresults "$pgrep" "(playlist)")
 # if there are playlists or videos, append them to list
 [ -n "$playlistids" ] && ids="$playlistids\n"
 [ -n "$videoids" ] && ids="$ids$videoids"
+
 # url prefix for videos and playlists
 videolink="https://youtu.be/"
 playlink="https://youtube.com/playlist?list="
+
 # prompt the results to user infinitely until they exit (escape)
 while true; do
 	clear
 	echo "Choose Video/Playlist to play: "
 	choice=$(echo -e "$ids" | cut -d'	' -f2 | $promptcmd) # dont show id
-	if [ -z "$choice" ]; then exit; fi	# if esc-ed then exit
+	if [ -z "$choice" ]; then break; fi	# if esc-ed then exit
 	id=$(echo -e "$ids" | grep -Fwm1 "$choice" | cut -d'	' -f1) # get id of choice
 	echo -e "$choice\t($id)"
 	case $id in
@@ -65,6 +80,7 @@ while true; do
 		???????????) mpv "$videolink$id";;
 		# 34 digit id = playlist
 		??????????????????????????????????) mpv "$playlink$id";;
-		*) exit ;;
+		*) break;;
 	esac
 done
+rm -f $responsecache
